services:
  # T-Mobile DE (Bootstrap Node - Leader)
  sp-tmobile-de:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: sp-tmobile-de
    ports:
      - "8081:8080"  # API port
      - "30301:30303"  # P2P port
    environment:
      - NODE_ID=tmobile-de
      - SETTLEMENT_THRESHOLD_EUR=100.0
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - P2P_PORT=30303
      - BOOTSTRAP_PEERS=""
    volumes:
      - ./persistent_data/tmobile-de:/app/data
      - ./zkp_keys/tmobile-de:/app/zkp_keys:ro
    networks:
      - sp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Vodafone UK
  sp-vodafone-uk:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: sp-vodafone-uk
    ports:
      - "8082:8080"  # API port
      - "30302:30303"  # P2P port
    environment:
      - NODE_ID=vodafone-uk
      - SETTLEMENT_THRESHOLD_EUR=100.0
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - P2P_PORT=30303
      - BOOTSTRAP_PEERS=sp-tmobile-de:30303
    volumes:
      - ./persistent_data/vodafone-uk:/app/data
      - ./zkp_keys/vodafone-uk:/app/zkp_keys:ro
    networks:
      - sp_network
    depends_on:
      - sp-tmobile-de
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Orange FR
  sp-orange-fr:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: sp-orange-fr
    ports:
      - "8083:8080"  # API port
      - "30303:30303"  # P2P port
    environment:
      - NODE_ID=orange-fr
      - SETTLEMENT_THRESHOLD_EUR=100.0
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - P2P_PORT=30303
      - BOOTSTRAP_PEERS=sp-tmobile-de:30303,sp-vodafone-uk:30303
    volumes:
      - ./persistent_data/orange-fr:/app/data
      - ./zkp_keys/orange-fr:/app/zkp_keys:ro
    networks:
      - sp_network
    depends_on:
      - sp-tmobile-de
      - sp-vodafone-uk
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Telefónica ES
  sp-telefonica-es:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: sp-telefonica-es
    ports:
      - "8084:8080"  # API port
      - "30304:30303"  # P2P port
    environment:
      - NODE_ID=telefonica-es
      - SETTLEMENT_THRESHOLD_EUR=100.0
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - P2P_PORT=30303
      - BOOTSTRAP_PEERS=sp-tmobile-de:30303,sp-vodafone-uk:30303,sp-orange-fr:30303
    volumes:
      - ./persistent_data/telefonica-es:/app/data
      - ./zkp_keys/telefonica-es:/app/zkp_keys:ro
    networks:
      - sp_network
    depends_on:
      - sp-tmobile-de
      - sp-vodafone-uk
      - sp-orange-fr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # SFR FR
  sp-sfr-fr:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: sp-sfr-fr
    ports:
      - "8085:8080"  # API port
      - "30305:30303"  # P2P port
    environment:
      - NODE_ID=sfr-fr
      - SETTLEMENT_THRESHOLD_EUR=100.0
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - P2P_PORT=30303
      - BOOTSTRAP_PEERS=sp-tmobile-de:30303,sp-vodafone-uk:30303,sp-orange-fr:30303,sp-telefonica-es:30303
    volumes:
      - ./persistent_data/sfr-fr:/app/data
      - ./zkp_keys/sfr-fr:/app/zkp_keys:ro
    networks:
      - sp_network
    depends_on:
      - sp-tmobile-de
      - sp-vodafone-uk
      - sp-orange-fr
      - sp-telefonica-es
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  sp_network:
    driver: bridge

volumes:
  sp_data_tmobile_de:
  sp_data_vodafone_uk:
  sp_data_orange_fr:
  sp_data_telenor_no:
  sp_data_sfr_fr: